# Generated by Django 6.0.4 on 2026-04-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_detallepedido_subtotal_pedido_cedula_facturacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
